version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: errly-postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-errly}
      POSTGRES_USER: ${DB_USER:-errly}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-errly_dev_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U errly -d errly"]
      interval: 10s
      timeout: 5s
      retries: 5

  clickhouse:
    image: clickhouse/clickhouse-server:23.8-alpine
    container_name: errly-clickhouse
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DATABASE:-errly_events}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-errly}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-errly_dev_password}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./database/clickhouse/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: errly-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  clickhouse_data:
  redis_data:

networks:
  default:
    name: errly-network
